project:
  type: website

website:
  title: "lekker"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Alex-Chisholm
      - icon: twitter
        href: https://twitter.com/chisholm1
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

execute:
  freeze: auto

